<h1>CMSC 197 - 1 | Lec01.1-Quiz1 </h1>

<h2>submitted by: John Patrick T. Panizales</h2>

In [2]:
import numpy as np
#try this

<h3>Part 1</h3>

<ul>
    <li>Create 2 2D arrays, y_hat and y</li>
    <li>Initialize y_hat with 20 linearly spaced numbers between -1 and 1</li>
    <li>Initialize y with 20 linearly spaced numbers between 0 and 1 </li>
</ul>

In [77]:
y_hat = np.linspace(-1,1, num=20)
y = np.linspace(0,1,num=20)

In [78]:
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [79]:
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<p>Compute for the shape and dimension of y_hat and y.</p>

In [233]:
shape1 = y_hat.shape
dim1 = y_hat.ndim
print("shape of y_hat: {}".format(shape1))
print("dimension of y_hat: {}".format(dim1))

shape of y_hat: (20,)
dimension of y_hat: 1


In [234]:
shape2 = y.shape
dim2 = y.ndim
print("shape of y: {}".format(shape2))
print("dimension of y: {}".format(dim2))

shape of y: (20,)
dimension of y: 1


<ul>
<li> Create individual functions for each of the loss functions with y and y_hat as parameters</li>
<li>Each function should return the loss value (L)</li>
</ul>

<h3>Mean Squared Error</h3>

In [218]:
def mse(y_hat, y):
    # y_hat - y
    subtract = y_hat - y
    
    # (y_hat - y) ^ 2
    squared = subtract ** 2
    
    # summation of (y_hat - y) ^ 2 from 1 to N
    summation = np.sum(squared)

    # mean squared error
    N = np.size(squared)
    L = summation/N
    
    return L

mse(y_hat,y)

0.3421052631578948

<h3>Mean Absolute Error (MAE)</h3>

In [223]:
def mae(y_hat, y):
    # y_hat - y
    subtract = y_hat - y
    
    # summation of |y_hat - y| from 1 to N
    summation = np.sum(np.absolute(subtract))
    
    # mean absolute error
    N = np.size(subtract)
    L = summation/N
    
    return L

mae(y_hat,y)

0.4999999999999999

<h3>Mean Squared Logarithmic Error</h3>

In [230]:
def msle(y_hat, y):
    if (np.all(y_hat >= 0)) and (np.all(y >= 0)):
        y_hat_plus1 = y_hat + 1
        y_plus1 = y + 1
        
        log_yhat = np.log10(y_hat_plus1)
        log_y = np.log10(y_plus1)
        #log(y_hat + 1) - log(y + 1)
        sub_logs = log_yhat - log_y
        squared = sub_logs ** 2
        
        # mean squared logarithmic error
        summation = np.sum(squared)
        N = np.size(squared)
        L = summation/N
        
    else:
        print("Cannot proceed with calculation. Values cannot be negative.")
    
msle(y_hat,y)

Cannot proceed with calucation. Values cannot be negative


<h3>Mean Absolute Percentage Error</h3>

In [275]:
def mape(y_hat, y):
    if(np.any(y == 0)):
        print("Cannot proceed. Values for y cannot be 0. Consider changing metric used.")
    else:
        sub_div = (y_hat - y)/y

        # summation of |(y_hat - y)/y| from 1 to N
        summation = np.sum(np.absolute(sub_div))

        # mean absolute error
        N = np.size(subtract)
        L = summation/N

        return L

mape(y_hat,y)

Cannot proceed. Values for y cannot be 0. Consider changing metric used.


<h3>Part 2</h3>

<p>1. Create a 1d array M {1, 2, …16} using the arange function</p>

In [7]:
M = np.array(np.arange(1,17))
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

<p>2. Reshape M into 4x4 array and store it to N</p>

In [9]:
N = M.reshape(4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

<p>3. Get the 2nd row of N</p>

In [284]:
second_row = N[1:2,]
second_row

array([[5, 6, 7, 8]])

<p>4. Get the minimum values for each column of N</p>

In [286]:
min_each_row = np.min(N, axis=0)
min_each_row

array([1, 2, 3, 4])

<p>5. Get the locations of the minimum values for each column of N</p>

In [290]:
for each_min in min_each_row:
    i,j = np.where(N == each_min)
    print(i,j)

[0] [0]
[0] [1]
[0] [2]
[0] [3]


<p>6. Get the average of the whole matrix</p>

In [29]:
ave = np.average(N)
ave

8.5

<p>7. Create a vector V with 4 elements, each element is 1</p>

In [152]:
V = np.array([1,1,1,1]);
V

array([1, 1, 1, 1])

<p>8. Take the dot product of N and V</p>

In [72]:
n_dot_v = np.dot(N,V)
n_dot_v

array([10, 26, 42, 58])